from view.constants import WIDTH, HEIGHT
GROUND_HEIGHT = WIDTH // 25.7
GROUND_Y_POS = HEIGHT - GROUND_HEIGHT
CAPYBARA_WIDTH = WIDTH // 9
CAPYBARA_HEIGHT = HEIGHT // 5
CAPYBARA_POS_X = WIDTH // 25
CAPYBARA_Y_POS = GROUND_Y_POS - CAPYBARA_HEIGHT
ENEMY_START_POS_X = WIDTH + 50
BEAR_WIDTH = WIDTH // 4.5
BEAR_HEIGHT = HEIGHT // 6.6
BEAR_POS_Y = GROUND_Y_POS - BEAR_HEIGHT
BIRD_WIDTH = WIDTH // 4.5
BIRD_HEIGHT = HEIGHT // 8
BIRD_CENTER_POS_Y = GROUND_Y_POS - CAPYBARA_HEIGHT - GROUND_HEIGHT - BIRD_HEIGHT
BIRD_TOP_POS_Y = BIRD_CENTER_POS_Y - (BIRD_HEIGHT * 2)
BIRD_BOTTOM_POS_Y = BIRD_CENTER_POS_Y + CAPYBARA_HEIGHT
